---
driver:
  name: vagrant
  provider: virtualbox
  gui: true
  username: vagrant
  password: vagrant
  network:
    - ["forwarded_port", {guest: 3389, host: 33389, auto_correct: true, id: "rdp"}]
  communicator: winrm
  basic_auth_only: true


provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows_10_pro
    driver:
      box: hoeggsoftware/windows_10_pro

suites:
  - name: default
    run_list:
      - recipe[default::default]
