---
driver:
  name: vagrant
  provider: virtualbox
  gui: true
  username: vagrant
  password: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-2012r2
    driver:
      box: mwrock/Windows2012R2

suites:
  - name: default
    run_list:
      - recipe[default::default]
